name: Update Google Scholar Citations

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  update-citations:
    uses: ./.github/workflows/update-profile-impact.yml
    secrets: inherit
